arthouse/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from home import views




urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.home, name='home'),
    url(r'^', include('contacts.urls', namespace='contacts')),
    url(r'^', include('gallery.urls', namespace='gallery')),
    url(r'^', include('gypsumProducts.urls', namespace='gypsum')),
    url(r'^', include('orders.urls', namespace='orders')),
    url(r'^', include('prices.urls', namespace='prices')),
    url(r'^', include('projects.urls', namespace='projects')),
    url(r'^', include('aboutus.urls', namespace='about_us')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
]
if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gypsumProducts/urls.py
from django.conf.urls import url
from .views import *


urlpatterns = [
    url(r'^gypsum_products/$', gypsum_products, name='gypsum_products'),
    url(r'^gypsum_product/(?P<id>\d+)/$', gypsum_detail, name='gypsum_detail'),
    url(r'^gypsum_category/(?P<id>\d+)/$', gypsum_in_category, name='gypsum_in_category'),
]

orders/urls.py
from django.conf.urls import url, include
from django.views.generic import TemplateView
from .views import *


urlpatterns = [
    url(r'^basket_adding/$', basket_adding, name='basket_adding'),
    url(r'^checkout/$', checkout, name='checkout'),
]

gypsumProducts/models.py
from ckeditor_uploader.fields import RichTextUploadingField
from django.db import models
from django.urls import reverse
from imagekit.models import ImageSpecField
from imagekit.processors import ResizeToFit


class GypsumCategory(models.Model):
    name = models.CharField(max_length=128, blank=True, null=True, default=None)
    tab_title = models.TextField('Заголовок закладки', blank=True, null=True)
    title = models.CharField(max_length=128, blank=True, null=True, default=None)
    short_description = RichTextUploadingField(blank=True, null=True, default=None)
    description = RichTextUploadingField(blank=True, null=True, default=None)
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True, auto_now=False)
    update = models.DateTimeField(auto_now=True, auto_now_add=False)

    def __str__(self):
        return ("%s") % self.name

    def get_absolute_url(self):
        return reverse('gypsum:gypsum_in_category', kwargs={'id': self.id})

    class Meta:
        verbose_name = 'Категорія ліпнини'
        verbose_name_plural = 'Категорії ліпнини'


class GypsumProduct(models.Model):
    name = models.CharField(max_length=64, blank=True, null=True, default=None)
    category = models.ForeignKey(GypsumCategory, blank=True, null=True, default=None, on_delete=models.CASCADE)
    gypsum_3d_model = models.FileField(upload_to="gypsum_3dmodels/", blank=True, null=True, default=None)
    tab_title = models.TextField('Заголовок закладки', blank=True, null=True)
    price = models.IntegerField(default=0)
    discount = models.IntegerField(default=0)
    short_description = RichTextUploadingField(blank=True, null=True, default=None)
    domentions = RichTextUploadingField(blank=True, null=True, default=None)
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True, auto_now=False)
    update = models.DateTimeField(auto_now=True, auto_now_add=False)

    def __str__(self):
        return ("%s, %s грн") % (self.name, self.price)

    def get_absolute_url(self):
        return reverse('gypsum:gypsum_detail', kwargs={'id': self.id})

    class Meta:
        verbose_name = 'Ліпнина'
        verbose_name_plural = 'Ліпнина'


class GypsumImage(models.Model):
    gypsum_product = models.ForeignKey(GypsumProduct, blank=True, null=True, default=None, on_delete=models.CASCADE)

    image = models.ImageField(upload_to="products_images/", blank=True, null=True, default=None)

    image_thumbnail = ImageSpecField(source='image',
                                      processors=[ResizeToFit(700)],
                                      format='JPEG',
                                      options={'quality': 60})

    is_active = models.BooleanField(default=True)
    is_main = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True, auto_now=False)
    update = models.DateTimeField(auto_now=True, auto_now_add=False)

    def __str__(self):
        return self.gypsum_product.name

    class Meta:
        verbose_name = 'Фото ліпнини'
        verbose_name_plural = 'Фотки ліпнини'


class PageGypsumDescription(models.Model):
    tab_title = models.TextField('Заголовок закладки', blank=True, null=True)
    title = models.CharField(max_length=128, blank=True, null=True)
    sub_title = RichTextUploadingField(max_length=128, blank=True, null=True)
    short_description = RichTextUploadingField(blank=True, null=True, default=None)
    description = RichTextUploadingField(blank=True, null=True, default=None)
    is_active = models.BooleanField(default=True)
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)
    update = models.DateTimeField(auto_now=True, auto_now_add=False)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Опис сторінки ліпнина'
        verbose_name_plural = 'Опис сторінки ліпнина'

gypsumProducts/views.py
from django.shortcuts import render, get_object_or_404
from urllib.parse import quote_plus
from .models import *

def gypsum_products(request):
	categories = GypsumCategory.objects.filter(is_active=True)

	title_description_model = PageGypsumDescription.objects.filter(is_active=True)[0]
	tab_title = title_description_model.tab_title
	title = title_description_model.title
	short_description = title_description_model.short_description
	description = title_description_model.description
	
	gypsum_products = GypsumProduct.objects.filter(is_active=True)

	context = {
			'categories': categories,
			'tab_title': tab_title,
			'title': title,
			'short_description':short_description,
			'description': description,
			'gypsum_products': gypsum_products,
		}

	return render(request, 'gypsum/gypsum_products.html', context)

def gypsum_detail(request, id=None):
	categories = GypsumCategory.objects.filter(is_active=True)
	gypsum_product = get_object_or_404(GypsumProduct, id=id)
	tab_title = gypsum_product.tab_title
	share_string = quote_plus("Проект ") + quote_plus(gypsum_product.name)
	if gypsum_product.short_description:
		share_string = quote_plus("Проект ") + quote_plus(gypsum_product.name) + quote_plus(" ") + quote_plus(gypsum_product.short_description)
	context = {
			'categories': categories,
			'gypsum_product': gypsum_product,
			'tab_title': tab_title,
			'share_string': share_string,
		}

	return render(request, 'gypsum/gypsum_detail.html', context)


def gypsum_in_category(request, id=None):
	categories = GypsumCategory.objects.filter(is_active=True)
	category = get_object_or_404(GypsumCategory, id=id)
	tab_title = category.tab_title
	gypsum_in_category = GypsumProduct.objects.filter(is_active=True, category_id = id)
	context = {
			'categories': categories,
			'tab_title': tab_title,
			'category':category,
			'gypsum_in_category': gypsum_in_category,
		}

	return render(request, 'gypsum/gypsum_in_category.html', context)

templates/gypsum/gypsum_detail.html
{% extends 'base.html' %}

{% block head_title %} {{ tab_title }} {% endblock %}

{% block sub_nav_bar %}

{% include 'gypsum/gypsum_navbar.html' %}

{% endblock sub_nav_bar %}



{% block breadcrumb %}

<div class="container">
	<nav aria-label="breadcrumb">
	  <ol class="breadcrumb">
	    <li class="breadcrumb-item"><a href="/">Головна</a></li>
	    <li class="breadcrumb-item"><a href="{% url 'gypsum:gypsum_products' %}">Проекти</a></li>
	    <li class="breadcrumb-item"><a href="{{ gypsum_product.category.get_absolute_url }}">{{ gypsum_product.category.name }}</a></li>
	    <li class="breadcrumb-item active" aria-current="page">{{ gypsum_product.name }}</li>
	  </ol>
	</nav>
</div>

{% endblock breadcrumb %}



{% block content %}
<br>
<div class="basket-container basket-container-sm container d-md-none d-lg-none d-xl-none">
    <a href="{% url 'orders:checkout' %}">Кошик <span id="basket_total_qnt">
        {% if total_product_qnt %}
            ({{ total_product_qnt }})
        {% else %}
            (0)
        {% endif %}
    </span></a>
</div>

	<div class="container">
		<div class="row">

			<div class="col-md-6">
				<div id="slider" class="flexslider">
				  <ul class="slides">
					{% for img in gypsum_product.gypsumimage_set.all %}
					    <li>
                            <img  src="{{ img.image.url }}" />
					    </li>
					{% endfor %}
				  </ul>
				</div>
				{% if gypsum_product.gypsumimage_set.all.1 %}
				<div id="carousel" class="flexslider d-none d-md-block d-xl-block">
				  <ul class="slides">
					{% for img in gypsum_product.gypsumimage_set.all %}
					    <li>
					      <img src="{{ img.image_thumbnail.url }}" />
					    </li>
					{% endfor %}
				  </ul>
				</div>
				{% endif %}
			</div>

			<div class="col-md-6 margin-bottom-65px">
				{% if gypsum_product.name %}
				<h1 class="text-left margin-top-0">{{ gypsum_product.name }}</h1>
				{% endif %}
				{% if gypsum_product.price %}
				<h5 class="text-left margin-top-0">Ціна {{ gypsum_product.price }} грн</h5>
				{% endif %}
				<div class="gypsum-description">
					<ul class="nav nav-tabs" id="myTab" role="tablist">
					  {% if gypsum_product.short_description %}
					  <li class="nav-item">
					    <a class="nav-link active nav-padding" id="description-tab" data-toggle="tab" href="#description" role="tab" aria-controls="description" aria-selected="true">Опис</a>
					  </li>
					  {% endif %}
					  {% if gypsum_product.domentions %}
					  <li class="nav-item ">
					    <a class="nav-link nav-padding" id="dementions-tab" data-toggle="tab" href="#dementions" role="tab" aria-controls="dementions" aria-selected="false">Розміри</a>
					  </li>
					  {% endif %}
					</ul>
					<div class="tab-content" id="myTabContent">
					  <div class="tab-pane fade show active" id="description" role="tabpanel" aria-labelledby="description-tab">
					  	{% if gypsum_product.short_description %}
		                	{{ gypsum_product.short_description|safe }}
		                {% endif %}
					  </div>
					  <div class="tab-pane fade" id="dementions" role="tabpanel" aria-labelledby="dementions-tab">
					  	{% if gypsum_product.domentions %}
			                {{ gypsum_product.domentions|safe }}
			            {% endif %}
					  </div>
				</div>

				<form action="{% url 'orders:basket_adding' %}" class="form-inline" id="form_buying_product">{% csrf_token %}
					<div class="form-group">
						<input type="number" min="1" value="1" id="product-qnt-input" class="form-control product-qnt-input" placeholder="Оберіть кількість">
					</div>

					<div class="form-group">
						<button type="submit" id="qnt-submit-btn" class="btn btn-success qnt-submit-btn"
						data-product_id='{{ gypsum_product.id }}'
						data-name='{{ gypsum_product.name }}'
						data-price='{{ gypsum_product.price }}'>До кошика</button>
					</div>
				</form>

				{% if gypsum_product.gypsum_3d_model %}
					<br>
					<a href="{{ gypsum_product.gypsum_3d_model.url }}" download>Скачати 3D модель</a>
				{% endif %}
				</div>
			</div>
		</div>

		
		<div class="social-likes-title">Поділитися проектом</div>
		<div class="row row-social-likes">
			<div class="col-md-3">
				<a href="https://www.facebook.com/sharer/sharer.php?u={{ request.build_absolute_uri }}" target="_blank">
					Share on Facebook
				</a>
				
			</div>

			<div class="col-md-3">
				<a href="https://twitter.com/home?status={{ share_string }}%20%20{{ request.build_absolute_uri }}" target="_blank">
					Share on Twitter
				</a>
			</div>

			<div class="col-md-3">
				<a href='https://plus.google.com/share?url={{ request.build_absolute_uri }}' target="_blank">
					Share on Google+ 
				</a>

				
			</div>
			<div class="col-md-3">
				<a data-pin-do="buttonBookmark" href="//www.pinterest.com/pin/create/button" target="_blank"><!-- <img src="//assets.pinterest.com/images/pidgets/pinit_fg_en_rect_gray_20.png" /> --></a>
			</div>
		</div>
	</div>



{% endblock content %}

{% block script %}

	{% load static %}
	<script src="{% static 'js/jquery.flexslider.js' %}"></script>

	<script type="text/javascript">
		$(document).ready(function() {
		  	 // The slider being synced must be initialized first
			  $('#carousel').flexslider({
			    animation: "slide",
			    controlNav: false,
			    animationLoop: false,
			    slideshow: false,
			    itemWidth: 210,
			    itemMargin: 5,
			    asNavFor: '#slider'
			  });
			 
			  $('#slider').flexslider({
			    animation: "slide",
			    controlNav: false,
			    animationLoop: false,
			    slideshow: false,
			    sync: "#carousel"
			  });

			  	$('.slides>li').html(function(i,h){
				    return h.replace(/&nbsp;/g,'');
				});
			});
	</script>


{% endblock script %}

templates/gypsum/gypsum_in_category.html
{% extends 'base.html' %}

{% block head_title %} {{ tab_title }} {% endblock %}


{% block sub_nav_bar %}

{% include 'gypsum/gypsum_navbar.html' %}

{% endblock sub_nav_bar %}



{% block breadcrumb %}
<div class="container">
	<nav aria-label="breadcrumb">
	  <ol class="breadcrumb">
	    <li class="breadcrumb-item"><a href="/">Головна</a></li>
	    <li class="breadcrumb-item"><a href="{% url 'gypsum:gypsum_products' %}">Проекти</a></li>
	    <li class="breadcrumb-item active" aria-current="page">{{ category.name }}</li>
	  </ol>
	</nav>
</div>

{% endblock breadcrumb %}



{% block content %}
    <div class="container">
		<div class="row">
			<div class="col-md-12">
				{% if category.name %}
				<h1 class="text-center page__title">{{ category.name }}</h1>
				{% endif %}
				<div class="basket-container container d-md-none d-lg-none d-xl-none">
				    <a href="{% url 'orders:checkout' %}">Кошик <span id="basket_total_qnt">
				        {% if total_product_qnt %}
				            ({{ total_product_qnt }})
				        {% else %}
				            (0)
				        {% endif %}
				    </span></a>
			    </div>   
				{% if category.short_description %}
                <p>{{ category.short_description|safe }} </p>
                {% endif %}
				{% if category.description %}
	            <div class="content hideContent">
	                <p>{{ category.description|safe }}</p>
	            </div>
	            <div class="show-more">
	                <a href="#" class="more-link">Детальніше</a>
	            </div>
	            {% endif %}
			</div>
		</div>
	</div>

	<div class="container-fluid">
		<div class="row">
			{% for gypsum_item in gypsum_in_category %}
				<div class="col-md-3 col-md-3-padding-0">
			      	{% for obj in gypsum_item.gypsumimage_set.all %}
				      	{% if obj.is_main %}
				        <div class="last-projects-img-size img-div">
				        	<a href="{{ gypsum_item.get_absolute_url }}">
				        		<img class="image-resize card-img-top-border-radius-0 img-zoom" style="height: auto;" src="{{ obj.image.url }}" alt="Card image cap">
				        	</a>
				        </div>

					    <div class="project__title">
				          <a href="{{ gypsum_item.get_absolute_url }}"><p>{{ gypsum_item.name }}</p></a>
				        </div>				        	
				        
				        {% endif %}
				    {% endfor %}
	        	</div>
	    	{% endfor %}
		</div>
	</div>


{% endblock content %}

templates/gypsum/gypsum_navbar.html
<nav class="navbar navbar-expand-md sub-nav-bar-sticky main-background-color d-none d-md-block d-xl-block">
  <div class="container">

        <ul class="navbar-nav mx-auto">
          {% for category in categories %}
          <li class="nav-item">
            <a class="nav-link" href="{{ category.get_absolute_url }}">{{ category.name }}</a>
          </li>
          {% endfor %}
        </ul>

        <div class="basket-container text-right">

          <div class="basket">{% csrf_token %}
            <a href="#">Кошик <span id="basket_total_qnt">
                {% if total_product_qnt %}
                    ({{ total_product_qnt }})
                {% else %}
                    (0)
                {% endif %}
            </span></a>
          </div>

          <div class="basket-items text-center hidden">
            <ul>
              {% for product_in_basket in products_in_basket %}
                <li>
                  {% for img in product_in_basket.product.gypsumimage_set.all %}
                    {% if forloop.first %}                              
                      <a data-fancybox="gallery" data-options='{"buttons": ["zoom","close"]}' data-caption="{{ products_in_basket.name }}" href="{{ img.image.url }}" class="outline-focus-none">
                          <img class="basket-img" src="{{ img.image_thumbnail.url }}" />
                      </a>
                    {% endif %}
                  {% endfor %}


                  <p class="basket-p">{{ product_in_basket }}, {{ product_in_basket.nmb }} шт. по {{ product_in_basket.price_pre_item }} грн <a class="delete-item" href="#" data-product_id="{{ product_in_basket.product.id }}"><sup title="Видалити">X</sup></a>
                  </p>
                </li>
              {% endfor %}
            </ul>
            <a role="button" class="basket-btn btn btn-success btn-sm" href="{% url 'orders:checkout' %}">До оформлення</a>
          </div>
        </div>
        

    </div>
  </nav>

templates/gypsum/gypsum_products.html
{% extends 'base.html' %}

{% block head_title %} {{ tab_title }} {% endblock %}


{% block sub_nav_bar %}

{% include 'gypsum/gypsum_navbar.html' %}

{% endblock sub_nav_bar %}


{% block breadcrumb %}

<div class="container">
	<nav aria-label="breadcrumb">
	  <ol class="breadcrumb">
	    <li class="breadcrumb-item"><a href="/">Головна</a></li>
	    <li class="breadcrumb-item active" aria-current="page">Ліпнина</li>
	  </ol>
	</nav>
</div>

{% endblock breadcrumb %}


{% block content %}

	<div class="container">
		<div class="row">
			<div class="col-md-12">
				{% if title %}
				<h1 class="text-center page__title">{{ title }}</h1>
				{% endif %}
				<div class="basket-container basket-container-sm container d-md-none d-lg-none d-xl-none">
				    <a href="{% url 'orders:checkout' %}">Кошик <span id="basket_total_qnt">
				        {% if total_product_qnt %}
				            ({{ total_product_qnt }})
				        {% else %}
				            (0)
				        {% endif %}
				    </span></a>
			    </div>
				{% if description %}
				<p>{{ short_description|safe }}</p>
				{% endif %}
				{% if description %}
	            <div class="content hideContent">
	                <p>{{ description|safe }}</p>
	            </div>
	            <div class="show-more">
	                 <a href="#" class="more-link margin-bottom-65px">Детальніше</a>
	            </div>
	            {% endif %}
			</div>
		</div>
	</div>
            


	<div class="container-fluid">
		<div class="row">
			{% for gypsum_item in gypsum_products %}
				<div class="col-md-3 col-md-3-padding-0">
			      	{% for obj in gypsum_item.gypsumimage_set.all %}
				      	{% if obj.is_main %}
				        <div class="img-div">
				        	<a href="{{ gypsum_item.get_absolute_url }}">
				        		<img class="card-img-top-border-radius-0 img-zoom" style="height: auto;" src="{{ obj.image.url }}" alt="Card image cap">
				        	</a>
				        </div>
				        {% endif %}
				    {% endfor %}

			        <div class="project__title">
			          <a href="{{ gypsum_item.get_absolute_url }}"><p>{{ gypsum_item.name }}</p></a>
			        </div>
	        	</div>
	    	{% endfor %}
		</div>
	</div>


{% endblock content %}